### ISSUE TITLE
GoogleTranslate.translate won't translate anything after dot.

### ISSUE THREAD

**Issue by vinhtq115** [goxr3plus/Java-Google-Text-To-Speech#2]
I tested this line of code:
`System.out.println(GoogleTranslate.translate("vi", "This time it will work. It worked"));`
And it only print out the translated first part of the text. Anything after the first dot won't be translated.
`Lần này nó sẽ hoạt động.`

**Comment by goxr3plus** [comment]
Hm must be a dependency problem with Guava or something... no errors?

**Comment by vinhtq115** [comment]
No. It seems like it only works with the first sentence.

Update: I tried with other languages and they don't translate the second either.

**Comment by goxr3plus** [comment]
Ou damn thanks for telling me my friend, i will try to do some tests.. Please help me on that... i have many projects and working ful time. Take a look and let me know if you find something interesting

**Comment by vinhtq115** [comment]
I think you should separate the Text translate into another project and use official Google API for it. In my app, I used Cloud Translation API and it worked pretty well. Here is the link from Google: [https://cloud.google.com/translate/docs/quickstart-client-libraries#client-libraries-install-java](url)

**Comment by vinhtq115** [comment]
Hey I found out why. In `com.darkprograms.speech.translator.GoogleTranslate` class, you have this function:
`public static String translate(String sourceLanguage, String targetLanguage, String text) throws IOException {
        String urlText = generateURL(sourceLanguage, targetLanguage, text);
        URL url = new URL(urlText);
        String rawData = urlToText(url);
        if (rawData == null) {
            return null;
        } else {
            String[] raw = rawData.split("\"");
            return raw.length < 2 ? null : raw[1];
        }
    }`

Since it only return raw[1], that means it only return the first sentence.

**Comment by goxr3plus** [comment]
ouuuu that's amazing we can fix it.

**Comment by goxr3plus** [comment]
@vinhtq115 Can you send me a pull request :) ? On https://github.com/goxr3plus/java-google-speech-api and i will accept and improve it :) so update with a new release for fixing your issue :)

**Comment by vinhtq115** [comment]
Can you instruct me how to do that? I haven’t do that before.

**Comment by goxr3plus** [comment]
You just have to rewrite the code for that method :) ? How good is your
programming skills :)?

**Comment by vinhtq115** [comment]
I have been studying for 2 months. Also, it seems like I can't edit the jar file directly in my IDE.

**Comment by goxr3plus** [comment]
Of course :) You have to go the the repository, the jar is produced from code :) The link i said you is a Maven repository which contains the code, when you modify the code you can actually rebuild the jar by running mvn clean package from the console. Many things you need to learn my friend :) When i forked it i was also a newbie

**Comment by vinhtq115** [comment]
I have rewrote the method and submitted a pull request.

**Comment by goxr3plus** [comment]
You are amazing :)!!!!
